main_app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('books/', views.book_index, name='index'),
    path('books/read', views.book_read, name='book_read' ),
    path('books/want_to_read', views.want_to_read, name='want_to_read' ),
    path('books/create', views.BookCreate.as_view(), name='books_create'),
    path('books/<int:book_id>', views.book_detail, name='detail'),
    path('books/<int:pk>/delete/', views.BookDelete.as_view(), name='books_delete'),
    path('books/<int:pk>/update/', views.BookUpdate.as_view(), name='books_update'),
    path('accounts/signup/', views.signup, name='signup'),
    path('books/<int:book_id>/add_reading', views.add_reading, name='add_reading')
]

myreads/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.

HAVE_READ = (
        ('Yes', 'Yes'),
        ('Want to read', 'Want to read')
    )
class Book(models.Model):
    name = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    publish_date = models.DateField()
    read = models.CharField(choices=HAVE_READ, max_length=15, default = HAVE_READ[0][0])
    class Meta:
        ordering = ['name']

    def already_read(self):
        return self.name.filter(read='Yes')

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'book_id': self.id})
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class LastRead(models.Model):
        date = models.DateField()
        num_stars = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ]
    )
        book = models.ForeignKey(Book, on_delete=models.CASCADE)
        def __str__(self):
            return f"{self.num_stars} on {self.date}"
        class Meta:
            ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import LastRead

class LastReadForm(ModelForm):
  class Meta:
    model = LastRead
    fields = ['date', 'num_stars']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Book
from django.forms import ModelForm
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LastReadForm

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def book_index(request):
    books = Book.objects.filter(user=request.user)
    return render(request, 'books/index.html', {'books': books})

@login_required
def book_read(request):
    books = Book.objects.filter(read="Yes", user=request.user)
    return render(request, 'books/read_index.html', {'books': books})

@login_required
def want_to_read(request):
    books = Book.objects.filter(read='Want to read', user=request.user)
    return render(request, 'books/want_to_read_index.html', {'books': books})

@login_required
def book_detail(request, book_id):
    book = Book.objects.get(id=book_id)
    lastread_form = LastReadForm()
    return render(request, 'books/detail.html', {'book': book, 'lastread_form': lastread_form})



def add_reading(request, book_id):
  # create the ModelForm using the data in request.POST
  form = LastReadForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_reading = form.save(commit=False)
    new_reading.book_id = book_id
    new_reading.save()
  return redirect('detail', book_id=book_id)


class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['name', 'genre', 'author', 'publish_date','description', 'read']    
    success_url = '/books/'
      # This inherited method is called when a
  # valid cat form is being submitted
    def form_valid(self, form):
    # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
        return super().form_valid(form)

class BookDelete(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = '/books/'

class BookUpdate(LoginRequiredMixin, UpdateView, ModelForm):
    model = Book
    fields = ['name', 'genre', 'author', 'read', 'description']

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<div class="about">
<h1>About My Reads</h1>
<hr />
<p>My Reads is an app designed to help users keep track of books they've read and books they want to read. Sign up
    and see for yourself!
</p>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>My Reads</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" /> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper light-blue darken-2">
          <ul>
            <li>
              <a href="/" class="left brand-logo">  My Reads</a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="/about">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'books_create' %}">Add a Book</a></li>
            <li><a href="{% url 'index' %}">All Books</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer  light-blue darken-2">
      <div class="right">
        All Rights Reserved, © My Reads
      </div>
    </footer>
  </body>
</html>

main_app/templates/books/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Book Details</h1>
<div class="row">
<div class="col s6">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ book.name }}</span>
    <p>Author: {{ book.author }}</p>
    <p>Genre: {{ book.genre }}</p>
    <p>Date Published: {{ book.publish_date }}</p>
    <p>Read? {{ book.read }}</p>
    <hr />
    <p>Description: {{ book.description }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'books_update' book.id %}">Edit</a>
    <a href="{% url 'books_delete' book.id %}">Delete</a>
  </div>
</div>
</div>
<div class="col s6 card">
  <form action="{% url 'add_reading' book.id %}" method="post">
    {% csrf_token %} {{ lastread_form.as_p }}
    <input type="submit" class="btn" value="Add Reading" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Last Read</th>
        <th>Rating /10 </th>
      </tr>
    </thead>
    <tbody>
      {% for reading in book.lastread_set.all %}
      <tr>
        <td>{{reading.date}}</td>
        <td>{{reading.num_stars}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
</script>
{% endblock %}

main_app/templates/books/index.html
{% extends 'base.html' %} {% block content %}

<h1>My Books</h1>

{% for book in books %}
<div class="card">
  <a href="{% url 'detail' book.id %}">
    <div class="card-content">
      <span class="card-title">{{ book.name }}</span>
      <p>Author: {{ book.author }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/books/read_index.html
{% extends 'base.html' %} {% block content %}
<a class='dropdown-trigger btn red' href="#" data-target='dropdown1'>Filter</a>
<ul id='dropdown1' class='dropdown-content'>
    <li><a href="{% url 'book_read'%}">Already Read</a></li>
    <li><a href="{% url 'want_to_read'%}">Want to Read</a></li>
</ul>
<h1>Books I've Finished</h1>

{% for book in books %}

<div class="card">
  <a href="{% url 'detail' book.id %}">
    <div class="card-content">
      <span class="card-title">{{ book.name }}</span>
      <p>Author: {{ book.author }}</p>
    </div>
  </a>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.dropdown-trigger');
      M.Dropdown.init(elems);
    });
</script>
{% endfor %} {% endblock %}

main_app/templates/books/want_to_read_index.html
{% extends 'base.html' %} {% block content %}

<a class='dropdown-trigger btn red' href="#" data-target='dropdown1'>Filter</a>
<ul id='dropdown1' class='dropdown-content'>
    <li><a href="{% url 'book_read'%}">Already Read</a></li>
    <li><a href="{% url 'want_to_read'%}">Want to Read</a></li>
</ul>
<h1>Books I want to read</h1>

{% for book in books %}

<div class="card">
  <a href="{% url 'detail' book.id %}">
    <div class="card-content">
      <span class="card-title">{{ book.name }}</span>
      <p>Author: {{ book.author }}</p>
    </div>
  </a>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('.dropdown-trigger');
      M.Dropdown.init(elems);
    });
</script>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Welcome!</h1>
<hr />
<h5>Sign in, sign up, or visit our About page to learn more</h5>


{% endblock %}

main_app/templates/main_app/book_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Book</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' book.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/book_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1 class = "card-panel light-blue darken-2">Add Book</h1>
{% endif %}
<form class="card-panel light-blue darken-2" action="" method="post" >
  {% csrf_token %}
  <table>
    {{ form.as_p }}
  </table>
  <input type="submit" value="Submit!" class="btn red" />


<script>
    var dateEl = document.getElementById('id_publish_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    var selectEl = document.getElementById('id_read');
    M.FormSelect.init(selectEl);
</script>
</form>
{% endblock %}